apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: imrdsc/stomatology-ufe
    newName: imrdsc/stomatology-ufe
    newTag: 2.5.1
  - name: imrdsc/stomatology-al-webapi
    newName: imrdsc/stomatology-al-webapi
    newTag: 1.1.1
replacements:
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: id-stomatology-ufe
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name: id-stomatology-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ":"
        index: 1
