apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-stomatology-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /id-openapi
            - name: BASE_URL
              value: /id-openapi-ui