apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: id-stomatology-ufe
spec:
  module-uri: http://id-stomatology-ufe.wac-hospital/build/stomatology-ufe.esm.js
                    
  navigation:
    - element: id-appointments-page 
      attributes:
        - name: api-base
          value: /id-api
      path: id-appointments-page      
      title: Zoznam termínov id   
      details: Spravuje zoznam termínov pre zubára a načítanie informacií o klientoch - xdiscantiny
  preload: false                   
  proxy: true                      
  hash-suffix: v1alpha1             